<?php

/**
 * @file
 * BREBO Europakozijn module hooks.
 */

/**
 * Implements hook_theme().
 */
function brebo_europakozijn_theme($existing, $type, $theme, $path): array {
  return [
    'brebo_europakozijn_configurator' => [
      'template' => 'brebo-europakozijn-configurator',
    ],
    'brebo_europakozijn_projectstukken' => [
      'template' => 'brebo-europakozijn-projectstukken',
    ],
    'brebo_europakozijn_project_result' => [
      'variables' => [
        'result' => NULL,
      ],
      'template' => 'brebo-europakozijn-project-result',
    ],
  ];
}
