<?php

declare(strict_types=1);

namespace Drupal\brebo_customer_service\Knowledge;

/**
 * Curated public knowledge seed.
 *
 * Public presentation and AI authority are deliberately separate. Every item
 * starts as editorial knowledge and requires explicit source validation and
 * human approval before KnowledgeApproval can expose it to BREBO AI.
 */
final class KnowledgeCatalog {

  public static function items(): array {
    return [
      'kozijnen' => [
        self::item('kozijnen-herstellen-of-vervangen', 'Wanneer is een bestaand kozijn nog goed te herstellen?', 'Zichtbare slijtage betekent niet automatisch dat een kozijn vervangen moet worden. De omvang, oorzaak en positie van de schade bepalen of duurzaam herstel nog logisch is.'),
        self::item('houtrot-kozijnen', 'Wat betekent houtrot in een kozijn?', 'Houtaantasting ontstaat niet zonder vocht. De belangrijkste vraag is daarom waardoor het hout langdurig vochtig kon worden.'),
        self::item('tocht-langs-kozijnen', 'Waarom voel ik tocht langs mijn kozijnen?', 'Tocht kan via draaiende delen, aansluitnaden, beglazing of de aansluiting tussen kozijn en gevel binnenkomen.'),
        self::item('schilderwerk-kozijnen', 'Wanneer vraagt schilderwerk meer dan een nieuwe verflaag?', 'Schilderwerk beschermt houten kozijnen, maar een nieuwe afwerklaag lost onderliggende vocht- of houtproblemen niet op.'),
        self::item('rubbers-kozijnen-vervangen', 'Wanneer moeten kozijnrubbers of dichtingen worden vervangen?', 'Uitgedroogde, vervormde of losgeraakte dichtingen kunnen tocht, geluid en waterdichtheid beïnvloeden, maar ook de afstelling van het raam of de deur speelt mee.'),
        self::item('hang-en-sluitwerk-kozijnen', 'Wanneer is hang- en sluitwerk aan onderhoud of vervanging toe?', 'Klemmen, speling, zwaar sluiten of onvoldoende aandruk kunnen wijzen op slijtage, verkeerde afstelling of vervorming van raam, deur of kozijn.'),
        self::item('aluminium-kozijnen-corrosie', 'Wat betekent corrosie of aantasting op aluminium kozijnen?', 'Verkleuring, putvorming of aantasting kan samenhangen met oppervlaktebehandeling, vervuiling, vochtbelasting of contact met andere materialen.'),
        self::item('levensduur-kozijnen', 'Hoe bepaal je de resterende levensduur van kozijnen?', 'Leeftijd alleen zegt te weinig. Materiaal, detaillering, onderhoud, vochtbelasting, gebruik en feitelijke conditie bepalen samen hoeveel technische levensduur nog resteert.'),
      ],
      'glas' => [
        self::item('condens-tussen-glasbladen', 'Wat betekent condens tussen de glasbladen?', 'Vocht of waas in de afgesloten ruimte tussen glasbladen wijst doorgaans op een probleem met de afdichting van het isolatieglas.'),
        self::item('hrpp-bestaande-kozijnen', 'Heeft HR++ glas zin in bestaande kozijnen?', 'Dat kan, maar alleen wanneer het bestaande kozijn en beglazingssysteem geschikt zijn en de maatregel past bij ventilatie en de overige gebouwschil.'),
        self::item('triple-glas-bestaande-kozijnen', 'Kan triple glas in bestaande kozijnen?', 'Soms wel, maar de grotere dikte en massa maken dit nadrukkelijk een technische geschiktheidsvraag.'),
        self::item('veiligheidsglas-wanneer', 'Wanneer is veiligheidsglas relevant?', 'De benodigde glasopbouw hangt onder meer samen met positie, gebruik en het risico dat personen tegen of door het glas kunnen vallen.'),
        self::item('thermische-breuk-glas', 'Hoe ontstaat een thermische breuk in glas?', 'Grote temperatuurverschillen binnen één ruit kunnen spanningen veroorzaken. Zonbelasting, schaduw, folie, verwarming en glasopbouw kunnen daarbij een rol spelen.'),
        self::item('geluidswerend-glas', 'Wanneer helpt geluidswerend glas echt?', 'Geluidswering hangt niet alleen van het glas af. Ook kierdichting, ventilatieroosters, kozijnen en gevelaansluitingen bepalen hoeveel geluid binnenkomt.'),
        self::item('lekkage-beglazing', 'Kan lekkage via de beglazing ontstaan?', 'Water kan binnendringen via glasafdichtingen, glaslatten, sponningen of afwatering, maar de zichtbare plek binnen hoeft niet de werkelijke intredeplaats te zijn.'),
        self::item('glasdikte-en-afmetingen', 'Waarom zijn afmetingen belangrijk bij de keuze van glas?', 'Grotere ruiten krijgen andere belastingen en vervormingen te verwerken. Afmetingen, positie, windbelasting, ondersteuning en glasopbouw moeten daarom samen worden beoordeeld.'),
      ],
      'gevel-aansluitingen' => [
        self::item('lekkage-rond-kozijn', 'Waar kan lekkage rond een kozijn vandaan komen?', 'Water dat naast of onder een kozijn zichtbaar wordt kan via meerdere routes zijn binnengekomen. De zichtbare vochtplek is daarom een startpunt, geen diagnose.'),
        self::item('kitvoegen-vervangen', 'Wanneer moeten kitvoegen worden vervangen?', 'Scheuren, onthechting, verharding of verlies van vervormingsvermogen kunnen betekenen dat de voeg zijn functie niet meer goed vervult.'),
        self::item('koudebrug-herkennen', 'Hoe herken je een mogelijke koudebrug?', 'Een koudebrug kan leiden tot een kouder binnenoppervlak en onder bepaalde omstandigheden tot condens of schimmel.'),
        self::item('scheuren-gevel', 'Wat zegt een scheur in de gevel?', 'Een scheur kan oppervlakkig zijn, samenhangen met materiaalbeweging of wijzen op beweging in de constructie.'),
        self::item('voegwerk-gevel-herstellen', 'Wanneer is voegwerk aan herstel toe?', 'Open, uitgesleten of loszittende voegen kunnen de vochtbelasting van de gevel vergroten. Niet iedere beschadigde voeg vraagt echter om volledig opnieuw voegen.'),
        self::item('afspattende-bakstenen', 'Wat betekent afspattend of beschadigd metselwerk?', 'Afspatting kan samenhangen met vocht, vorst, zoutbelasting, materiaalkeuze of lokale detaillering. De oorzaak bepaalt of plaatselijk herstel voldoende is.'),
        self::item('vocht-in-spouwmuur', 'Hoe kan vocht via een spouwmuur binnenkomen?', 'Water kan via buitenspouwblad, vervuiling, spouwankers, isolatie, lateien of aansluitdetails naar binnen worden geleid. Een vochtplek bewijst daarom niet direct waar het probleem begint.'),
        self::item('dilatatievoegen-gevel', 'Waarom zijn dilatatievoegen in een gevel belangrijk?', 'Gevelmaterialen bewegen door temperatuur, vocht en vervorming. Dilataties moeten die beweging gecontroleerd opnemen en kunnen bij gebreken tot scheurvorming of lekkage leiden.'),
      ],
      'onderhoud-renovatie' => [
        self::item('onderhoud-of-renovatie', 'Wanneer wordt terugkerend onderhoud een renovatievraag?', 'Wanneer dezelfde problemen blijven terugkomen of verschillende bouwdelen tegelijk aandacht vragen, kan een samenhangende aanpak doelmatiger worden.'),
        self::item('schilderwerk-plannen', 'Hoe bepaal je wanneer buitenschilderwerk nodig is?', 'Oriëntatie, detaillering, materiaal, eerdere behandeling en feitelijke conditie bepalen wanneer onderhoud nodig wordt.'),
        self::item('planmatig-of-correctief', 'Wat is het verschil tussen planmatig en correctief onderhoud?', 'Correctief onderhoud reageert op een defect. Planmatig onderhoud organiseert werkzaamheden vooraf op basis van conditie, risico en verwachte levensduur.'),
        self::item('onderhoud-bundelen', 'Wanneer is het slim onderhoudswerkzaamheden te bundelen?', 'Bundelen kan voordeel geven wanneer werkzaamheden dezelfde bereikbaarheid, bouwdelen of uitvoeringsperiode delen.'),
        self::item('bouwbegeleiding-wanneer', 'Wanneer is onafhankelijke bouwbegeleiding zinvol?', 'Bouwbegeleiding is vooral waardevol wanneer kwaliteit, planning, kosten en technische keuzes tijdens de uitvoering actief bewaakt moeten worden namens de opdrachtgever.'),
        self::item('bouwbegeleiding-controlepunten', 'Wat controleert een bouwbegeleider tijdens de uitvoering?', 'De controle richt zich onder meer op afgesproken kwaliteit, technische details, voortgang, afwijkingen, meerwerk, vastlegging en tijdige besluitvorming.'),
        self::item('oplevering-restpunten', 'Hoe voorkom je discussie over restpunten bij oplevering?', 'Heldere eisen, tussentijdse controles, foto- en dossieropbouw en een eenduidige opname bij oplevering maken zichtbaar wat gereed is en wat nog moet worden hersteld.'),
        self::item('renovatie-bewoners-hinder', 'Hoe beperk je hinder tijdens onderhoud of renovatie?', 'Goede fasering, bereikbaarheid, communicatie, werkvolgorde en afspraken over veiligheid en gebruik zijn nodig om werkzaamheden uitvoerbaar te houden voor bewoners en gebruikers.'),
      ],
      'verduurzaming' => [
        self::item('glas-vervangen-verduurzamen', 'Is alleen het glas vervangen een goede verduurzamingsmaatregel?', 'Beter isolerend glas kan warmteverlies en comfort verbeteren, maar het resultaat hangt ook af van kozijnen, kierdichting, gevel en ventilatie.'),
        self::item('isoleren-en-ventileren', 'Waarom moet ventilatie mee bij isoleren?', 'Isolatie en kierdichting beperken warmteverlies, terwijl vocht en verontreinigde binnenlucht gecontroleerd moeten kunnen worden afgevoerd.'),
        self::item('gevelisolatie-aandachtspunten', 'Waar moet je op letten bij gevelisolatie?', 'Gevelisolatie verandert niet alleen de isolatiewaarde, maar ook aansluitingen, vochtgedrag, detaillering en het uiterlijk van de gevel.'),
        self::item('verduurzamen-in-volgorde', 'In welke volgorde kun je een gebouw verduurzamen?', 'De logische route volgt uit conditie, energieverlies, onderhoudsmomenten, technische afhankelijkheden en budget.'),
        self::item('kierdichting-verduurzamen', 'Hoe belangrijk is kierdichting bij verduurzaming?', 'Ongecontroleerde luchtlekken kunnen comfort en energieprestatie sterk beïnvloeden. Kierdichting moet wel samengaan met voldoende en beheerste ventilatie.'),
        self::item('spouwmuur-naisoleren', 'Wanneer is na-isolatie van een spouwmuur verstandig?', 'Geschiktheid hangt af van spouwbreedte, vervuiling, vochtbelasting, gevelconditie, blootstelling en aanwezige isolatie. Eerst onderzoeken voorkomt dat bestaande problemen worden opgesloten.'),
        self::item('zonwering-oververhitting', 'Wanneer hoort zonwering bij verduurzaming?', 'Een beter geïsoleerd gebouw kan warmte langer vasthouden. Zonbelasting, glasoppervlak, oriëntatie en gebruik bepalen of beperking van oververhitting onderdeel van het plan moet zijn.'),
        self::item('verduurzaming-combineren-onderhoud', 'Waarom verduurzaming combineren met gepland onderhoud?', 'Wanneer een bouwdeel toch wordt aangepakt, kunnen bereikbaarheid, afwerking en vervangingsmoment worden benut om energetische verbeteringen doelmatiger mee te nemen.'),
      ],
      'gebouwbeheer' => [
        self::item('mjop-wat-is-het', 'Wat hoort een MJOP eigenlijk te doen?', 'Een meerjarenonderhoudsplan helpt toekomstige onderhoudsbehoefte, timing en financiële reservering inzichtelijk te maken.'),
        self::item('gebrek-urgent', 'Wanneer is een gebrek urgent?', 'Urgentie wordt onder meer bepaald door veiligheid, kans op gevolgschade, snelheid van verslechtering en invloed op gebruik.'),
        self::item('inspectie-frequentie', 'Hoe vaak moet een gebouw worden geïnspecteerd?', 'Een zinvolle inspectiefrequentie hangt af van bouwdeel, conditie, risico, omgeving, gebruik en onderhoudsstrategie.'),
        self::item('onderhoud-prioriteren', 'Hoe prioriteer je onderhoud als niet alles tegelijk kan?', 'Prioriteren betekent gevolgen vergelijken. Veiligheid, waterdichtheid, verdere schade, continuïteit en financiële efficiency kunnen meewegen.'),
        self::item('conditiemeting-gebouw', 'Wat vertelt een conditiemeting wel en niet?', 'Een conditiescore helpt de technische staat gestructureerd vast te leggen, maar vervangt geen beoordeling van oorzaak, risico, functie en passende maatregel.'),
        self::item('onderhoudsbudget-reserveren', 'Hoe bepaal je een realistische onderhoudsreservering?', 'Een bruikbare reservering volgt uit verwachte maatregelen, prijsniveau, onzekerheid, planning en risico. Alleen historische uitgaven doortrekken geeft vaak een vertekend beeld.'),
        self::item('onderhoud-uitstellen-risico', 'Wat zijn de risico’s van onderhoud uitstellen?', 'Uitstel kan verantwoord zijn wanneer risico en ontwikkeling beperkt zijn, maar kan ook leiden tot gevolgschade, hogere kosten, veiligheidsproblemen of verlies van functionaliteit.'),
        self::item('gebouw-dossier-opbouwen', 'Welke informatie hoort in een goed gebouw- en onderhoudsdossier?', 'Inspecties, tekeningen, foto’s, garanties, onderhoudshistorie, besluiten, offertes, uitgevoerde maatregelen en revisiegegevens vormen samen de basis voor controleerbaar gebouwbeheer.'),
      ],
    ];
  }

  public static function find(string $slug): ?array {
    foreach (self::items() as $topic => $items) {
      foreach ($items as $item) {
        if ($item['slug'] === $slug) {
          return $item + ['topic' => $topic];
        }
      }
    }
    return NULL;
  }

  public static function aiItems(): array {
    $approved = [];
    foreach (self::items() as $topic => $items) {
      foreach ($items as $item) {
        $item += ['topic' => $topic];
        if (KnowledgeApproval::isAiApproved($item)) {
          $approved[] = $item;
        }
      }
    }
    return $approved;
  }

  private static function guidance(string $slug): array {
    $guidance = [
      'kozijnen-herstellen-of-vervangen' => [['Begin bij oorzaak en omvang', 'Afbladderende verf, open verbindingen of plaatselijke aantasting zijn niet automatisch een reden voor volledige vervanging. Bepaal eerst welk deel is aangetast, hoe diep de schade gaat en waardoor die is ontstaan.'], ['Vergelijk herstel met resterende levensduur', 'Herstel is vooral logisch wanneer voldoende gezond materiaal aanwezig blijft, de oorzaak duurzaam kan worden weggenomen en het overige kozijn nog een passende levensduur heeft.'], ['Kijk ook naar toekomstige eisen', 'Beglazing, kierdichting, beslag en gepland gevelonderhoud kunnen de keuze beïnvloeden. Een technisch herstel kan minder logisch zijn wanneer kort daarna een grotere ingreep nodig is.']],
      'houtrot-kozijnen' => [['Zoek eerst de vochtbron', 'Houtrot is een gevolg van langdurige vochtbelasting. Kijk daarom naar schilderwerk, open verbindingen, glasafdichting, detaillering, afwatering en aansluitingen voordat alleen het aangetaste hout wordt hersteld.'], ['Bepaal de werkelijke omvang', 'Zichtbare aantasting kan kleiner zijn dan de schade in het hout. Plaats, diepte en kwaliteit van het omliggende materiaal bepalen of plaatselijk herstel technisch verantwoord is.'], ['Herstel oorzaak én materiaal', 'Alleen rot hout vervangen zonder de vochtbelasting weg te nemen geeft kans op herhaling. De reparatie moet daarom onderdeel zijn van een complete herstelmaatregel.']],
      'tocht-langs-kozijnen' => [['Lokaliseer de luchtlek', 'Tocht kan ontstaan bij draaiende delen, rubbers, glaslatten, aansluitnaden of de overgang tussen kozijn en gevel. Vaststellen waar lucht binnenkomt voorkomt dat op de verkeerde plek wordt afgedicht.'], ['Controleer afstelling en vervorming', 'Een nieuw rubber helpt niet wanneer een raam of deur onvoldoende aandrukt, is vervormd of verkeerd staat afgesteld. Beslag en maatvoering horen daarom bij de controle.'], ['Dicht niet zonder naar ventilatie te kijken', 'Ongecontroleerde kieren beperken is meestal wenselijk, maar aanwezige ventilatievoorzieningen moeten hun functie behouden.']],
      'schilderwerk-kozijnen' => [['Beoordeel meer dan de verflaag', 'Bladdering, scheuren, open verbindingen en verkleuring kunnen wijzen op vocht of onderliggende aantasting. Alleen overschilderen kan het probleem tijdelijk aan het zicht onttrekken.'], ['Kijk naar belasting per gevel', 'Zon, regen, detaillering en ligging verschillen per gevel en onderdeel. Daardoor hoeft niet ieder kozijn op hetzelfde moment dezelfde behandeling nodig te hebben.'], ['Koppel schilderwerk aan technisch herstel', 'Herstel van kit, verbindingen, houtschade en beglazingsdetails hoort vóór of tijdens het schilderwerk te worden meegenomen wanneer die onderdelen de bescherming beïnvloeden.']],
      'rubbers-kozijnen-vervangen' => [['Controleer eerst de sluiting', 'Een kier bij een rubber kan komen door veroudering van de dichting, maar ook door verkeerde afstelling, vervorming of onvoldoende aandruk van het draaiende deel.'], ['Beoordeel profiel en aansluiting', 'Vervangende dichtingen moeten passen bij profiel, sponning en benodigde vervorming. Alleen een dikker rubber toepassen is niet automatisch een goede oplossing.'], ['Test na herstel de functie', 'Na vervanging of afstelling moeten bediening, sluitdruk en aansluiting opnieuw worden gecontroleerd.']],
      'hang-en-sluitwerk-kozijnen' => [['Maak onderscheid tussen afstellen en slijtage', 'Klemmen of zwaar sluiten kan door afstelling komen, terwijl speling of beschadigde onderdelen op slijtage kan wijzen. Eerst vaststellen voorkomt onnodige vervanging.'], ['Controleer het complete draaiende deel', 'Scharnieren, sluitpunten, beslag, bevestigingen en vervorming van raam of deur werken samen. Een probleem op één punt kan elders worden veroorzaakt.'], ['Neem veiligheid en gebruik mee', 'Bij intensief gebruik, vluchtfuncties of bereikbare geveldelen kunnen andere eisen relevant zijn dan bij een weinig gebruikt raam.']],
      'aluminium-kozijnen-corrosie' => [['Bepaal welk type aantasting zichtbaar is', 'Oppervlaktevervuiling, beschadiging van de coating en daadwerkelijke corrosie vragen niet dezelfde aanpak. Plaats en patroon geven aanwijzingen over de oorzaak.'], ['Controleer materiaalcontact en vocht', 'Contact met andere materialen, zouten, blijvende vochtbelasting en beschadigde oppervlaktebehandeling kunnen aantasting versnellen.'], ['Herstel pas na oorzaakanalyse', 'Reinigen of lokaal bijwerken heeft weinig waarde wanneer de belastende situatie blijft bestaan.']],
      'levensduur-kozijnen' => [['Gebruik leeftijd niet als vervangingscriterium', 'Twee even oude kozijnen kunnen door materiaal, ligging, detaillering en onderhoud een sterk verschillende conditie hebben.'], ['Beoordeel kritieke onderdelen', 'Dorpels, verbindingen, draaiende delen, afdichtingen, beglazing en gevelaansluitingen geven samen een beter beeld van de resterende bruikbaarheid.'], ['Koppel levensduur aan het onderhoudsscenario', 'De relevante vraag is niet alleen hoe lang het kozijn technisch nog mee kan, maar ook welke onderhoudskosten en toekomstige prestaties daarbij horen.']],
      'condens-tussen-glasbladen' => [['Bepaal eerst waar de condens zit', 'Condens aan de binnenzijde, buitenzijde en tussen de glasbladen heeft niet dezelfde betekenis. Vocht of waas tussen de glasbladen bevindt zich in de afgesloten spouw van het isolatieglas.'], ['Kijk ook naar de beglazing als systeem', 'Bij vervanging is het verstandig ook randafdichting, glasoplegging, sponning en vochtbelasting rondom de ruit te beoordelen.'], ['Controleer voordat u vervangt', 'Leg vast welke ruit is aangedaan en controleer maat, glasopbouw en toestand van het kozijn zodat vervanging niet op aannames wordt besteld.']],
      'hrpp-bestaande-kozijnen' => [['Controleer eerst het bestaande kozijn', 'Sponning, glaslatten, ondersteuning, kierdichting en staat van het kozijn bepalen mede of een andere glasopbouw passend kan worden aangebracht.'], ['Neem ventilatie mee', 'Een betere isolatie en luchtdichtheid veranderen het comfort en de vochtbalans. Gecontroleerde ventilatie blijft daarom onderdeel van de beoordeling.'], ['Controleer maat en gewicht', 'Dikte, gewicht en randvoorwaarden van de nieuwe ruit moeten passen bij kozijn en draaiende delen.']],
      'triple-glas-bestaande-kozijnen' => [['Controleer ruimte en draagvermogen', 'Triple glas is doorgaans dikker en zwaarder dan bestaande isolerende beglazing. Sponning, glaslatten, beslag en ondersteuning moeten daarvoor geschikt zijn.'], ['Vergelijk de meerwaarde met de rest van de gevel', 'Een hoge glasprestatie levert niet automatisch hetzelfde resultaat wanneer kozijn, aansluitingen of andere geveldelen duidelijk minder presteren.'], ['Neem uitvoering mee in de keuze', 'Bereikbaarheid, ruitafmetingen en montagegewicht kunnen bepalen of een theoretisch mogelijke oplossing praktisch verstandig is.']],
      'veiligheidsglas-wanneer' => [['Begin bij positie en gebruik', 'De noodzaak en soort veiligheidsglas hangen samen met waar de ruit zit en hoe mensen ermee in aanraking kunnen komen.'], ['Maak onderscheid tussen risico’s', 'Letselbeperking, doorvalbeveiliging, inbraakvertraging en andere functies vragen niet automatisch dezelfde glasopbouw.'], ['Leg de projectsituatie vast', 'Afmetingen, onderzijde en bovenzijde van het glas, gebruiksfunctie en aangrenzende vloer- of loopzones zijn relevante invoer voor een juiste beoordeling.']],
      'thermische-breuk-glas' => [['Zoek naar temperatuurverschillen', 'Een thermische breuk kan ontstaan wanneer delen van dezelfde ruit sterk verschillend opwarmen. Zon en schaduw, verwarming, folie of objecten dicht achter het glas kunnen bijdragen.'], ['Sluit andere breukoorzaken niet uit', 'Breukbeeld en omstandigheden moeten worden beoordeeld; niet iedere spontane glasbreuk is automatisch thermisch.'], ['Beoordeel de vervangende glaskeuze', 'Als de belasting blijft bestaan, moet bij vervanging worden bekeken of glasopbouw of situatie moet worden aangepast.']],
      'geluidswerend-glas' => [['Bepaal eerst de geluidsbron', 'Verkeer, stemgeluid en andere bronnen hebben verschillende karakteristieken. Het gewenste resultaat moet daarom concreet worden gemaakt.'], ['Zoek de zwakste route', 'Kieren, ventilatieroosters, lichte panelen en gevelaansluitingen kunnen het effect van beter glas beperken.'], ['Beoordeel de complete gevelopbouw', 'Een glaskeuze is pas zinvol wanneer duidelijk is welke prestatie de overige onderdelen kunnen ondersteunen.']],
      'lekkage-beglazing' => [['Volg de waterroute', 'Water bij een glasrand kan via afdichting, glaslat, sponning of afwatering binnenkomen en zich verplaatsen voordat het zichtbaar wordt.'], ['Controleer beglazingsdetails', 'Afdichtingen, steun- en stelblokjes, glaslatten, ontwatering en toestand van de sponning horen bij de beoordeling.'], ['Herstel niet alleen de zichtbare kier', 'Extra kit aanbrengen zonder de waterhuishouding te begrijpen kan het probleem verplaatsen of afwatering blokkeren.']],
      'glasdikte-en-afmetingen' => [['Leg de geometrie correct vast', 'Breedte, hoogte, glasopbouw en positie zijn basisgegevens. Bij afwijkende vormen of grote ruiten zijn ook ondersteuning en randvoorwaarden relevant.'], ['Beoordeel de belasting', 'Wind, eigen gewicht, gebruik en eventuele veiligheidsfunctie beïnvloeden de benodigde opbouw.'], ['Laat twijfel berekenen', 'Wanneer vuistregels of standaardopbouwen onvoldoende zekerheid geven, is projectspecifieke technische controle nodig.']],
      'lekkage-rond-kozijn' => [['Begin buiten én binnen', 'Leg de zichtbare vochtplek binnen vast, maar controleer ook de buitenzijde en bovengelegen aansluitingen. Water kan zich door constructies verplaatsen.'], ['Koppel het probleem aan omstandigheden', 'Windrichting, regenintensiteit en moment van optreden helpen onderscheid maken tussen mogelijke routes.'], ['Test gericht wanneer kijken niet genoeg is', 'Bij een onduidelijke route kan gericht aanvullend onderzoek nodig zijn voordat herstel wordt gekozen.']],
      'kitvoegen-vervangen' => [['Beoordeel hechting en vervorming', 'Scheuren, loslaten, verharding en vervorming zeggen meer dan verkleuring alleen.'], ['Controleer de voeggeometrie', 'Breedte, diepte, rugvulling en aansluiting op de ondergrond beïnvloeden hoe de voeg beweging kan opnemen.'], ['Los de oorzaak van overbelasting op', 'Een nieuwe kitvoeg faalt opnieuw wanneer beweging, vocht of slechte ondergrond niet wordt meegenomen.']],
      'koudebrug-herkennen' => [['Kijk naar patroon en omstandigheden', 'Een plaatselijk koud oppervlak, condens of schimmel kan op een thermisch zwakke plek wijzen, maar gebruik en binnenklimaat beïnvloeden hetzelfde beeld.'], ['Vergelijk binnen- en buitensituatie', 'Constructieopbouw, aansluitdetails, temperatuur en luchtvochtigheid zijn nodig om een vermoeden beter te onderbouwen.'], ['Meet wanneer de oorzaak onzeker blijft', 'Oppervlaktetemperatuur, vocht en eventueel thermografisch onderzoek kunnen helpen, mits de meetomstandigheden geschikt zijn.']],
      'scheuren-gevel' => [['Leg vorm en verloop vast', 'Richting, breedte, lengte en plaats van een scheur geven informatie over mogelijke beweging.'], ['Kijk of de scheur actief is', 'Een oude stabiele scheur vraagt een andere benadering dan scheurvorming die aantoonbaar verder ontwikkelt.'], ['Herstel pas na duiding', 'Dichtsmeren zonder oorzaak te begrijpen kan alleen het symptoom tijdelijk verbergen. Bij twijfel over constructieve betekenis is specialistische beoordeling nodig.']],
      'voegwerk-gevel-herstellen' => [['Bepaal de omvang', 'Plaatselijk uitgesleten voegwerk is iets anders dan brede aantasting over een gevelvlak.'], ['Controleer metselwerk en vochtbelasting', 'Voegen functioneren samen met stenen, detaillering en waterbelasting. Alleen het voegmateriaal beoordelen is te beperkt.'], ['Kies herstel passend bij bestaand werk', 'Materiaal, hardheid, voegprofiel en uitvoeringsmethode moeten aansluiten bij het bestaande metselwerk.']],
      'afspattende-bakstenen' => [['Onderzoek vocht en belasting', 'Afspatting kan meerdere oorzaken hebben. Leg ligging, patroon, vochtbelasting en toestand van omliggende stenen vast.'], ['Bepaal of het lokaal of structureel terugkomt', 'Enkele beschadigde stenen kunnen plaatselijk worden aangepakt; herhaald patroon vraagt om onderzoek naar achterliggende omstandigheden.'], ['Voorkom cosmetisch herstel zonder oorzaak', 'Alleen beschadigde oppervlakken bijwerken helpt niet wanneer vocht- of vorstbelasting blijft bestaan.']],
      'vocht-in-spouwmuur' => [['Zoek de route door de gevel', 'Regenwater kan via verschillende onderdelen in of door de spouw worden geleid. De binnenvlek is daarom geen bewijs van de intredeplaats.'], ['Controleer details en vervuiling', 'Aansluitingen, lateien, spouwankers, isolatie en mogelijke speciebaarden kunnen relevant zijn.'], ['Onderzoek gericht bij verborgen oorzaken', 'Wanneer de spouw niet zichtbaar beoordeeld kan worden, kan plaatselijk nader onderzoek nodig zijn voordat herstel wordt bepaald.']],
      'dilatatievoegen-gevel' => [['Controleer of beweging kan worden opgenomen', 'Een dilatatie moet voldoende ruimte en een passend voegdetail hebben om verwachte beweging te kunnen volgen.'], ['Let op scheuren naast de voeg', 'Scheurvorming nabij een dilatatie kan erop wijzen dat beweging niet op de bedoelde plaats wordt opgenomen.'], ['Beoordeel de volledige voeg', 'Afdichting, ondergrond, continuïteit en aansluitingen aan kozijnen of andere bouwdelen horen bij de controle.']],
      'onderhoud-of-renovatie' => [['Kijk naar herhaling en samenhang', 'Wanneer dezelfde reparaties terugkomen of meerdere bouwdelen elkaar beïnvloeden, wordt alleen incidentgericht herstellen steeds minder logisch.'], ['Vergelijk scenario’s', 'Directe kosten zijn niet het enige criterium. Ook resterende levensduur, gevolgschade, bereikbaarheid, hinder en toekomstige onderhoudsbehoefte horen in de afweging.'], ['Maak de keuze controleerbaar', 'Leg per scenario vast wat wordt hersteld, welke prestatie wordt verwacht en welke risico’s of werkzaamheden blijven staan.']],
      'schilderwerk-plannen' => [['Plan op conditie, niet alleen kalender', 'Vaste cycli zijn een hulpmiddel, maar ligging, materiaal en actuele staat bepalen of onderhoud eerder of later nodig is.'], ['Inspecteer kwetsbare details', 'Onderkanten, verbindingen, glasdetails en horizontale delen kunnen sneller achteruitgaan dan grote zichtvlakken.'], ['Combineer met technisch herstel', 'Schilderwerk is het juiste moment om kleine gebreken te herstellen voordat ze groter worden.']],
      'planmatig-of-correctief' => [['Gebruik correctief onderhoud bewust', 'Een defect herstellen wanneer het optreedt kan passend zijn bij laag risico en beperkte gevolgschade.'], ['Plan waar uitval of schade duur wordt', 'Bij kritieke bouwdelen helpt vooraf plannen om veiligheid, waterdichtheid, bereikbaarheid en budget beter te beheersen.'], ['Combineer beide strategieën', 'Niet ieder onderdeel hoeft dezelfde onderhoudsstrategie te krijgen. Risico en functie bepalen wat logisch is.']],
      'onderhoud-bundelen' => [['Zoek gedeelde kosten en hinder', 'Steiger, hoogwerker, afzetting, bewonerscommunicatie en bereikbaarheid kunnen meerdere werkzaamheden bedienen.'], ['Controleer technische volgorde', 'Bundelen is alleen voordelig wanneer werkzaamheden elkaar niet hinderen en details in de juiste volgorde worden uitgevoerd.'], ['Vergelijk totaal in plaats van losse posten', 'Neem ook toekomstige bereikbaarheid, resterende levensduur en herhaling van hinder mee in de afweging.']],
      'bouwbegeleiding-wanneer' => [['Zorg voor regie vóórdat de uitvoering begint', 'Onafhankelijke bouwbegeleiding is vooral waardevol wanneer u als opdrachtgever grip wilt houden op kwaliteit, planning, kosten en technische keuzes zonder zelf dagelijks op het werk aanwezig te zijn.'], ['Controleer tijdens het werk, niet alleen achteraf', 'Door afspraken, details, afwijkingen en voortgang tijdens de uitvoering vast te leggen, kunnen problemen worden bijgestuurd voordat ze bij oplevering tot discussie, herstelwerk of extra kosten leiden.'], ['Spreek bevoegdheden vooraf af', 'Leg vast wie mag besluiten, welke afwijkingen eerst akkoord nodig hebben en hoe bevindingen worden teruggekoppeld.']],
      'bouwbegeleiding-controlepunten' => [['Maak vooraf duidelijk wat gecontroleerd wordt', 'De controlepunten volgen uit contractstukken, tekeningen, technische eisen, planning en kritieke uitvoeringsmomenten. Zo is vooraf duidelijk waarop de uitvoering wordt beoordeeld.'], ['Leg afwijkingen en besluiten aantoonbaar vast', 'Foto’s, bevindingen, afspraken, meer- en minderwerk en openstaande acties horen in één dossier.'], ['Controleer op het juiste moment', 'Sommige details zijn na dichtzetten niet meer zichtbaar. De planning van controles moet daarom aansluiten op kritieke uitvoeringsmomenten.']],
      'oplevering-restpunten' => [['Begin de oplevering al tijdens de uitvoering', 'Tussentijdse controles maken gebreken en onafgemaakte onderdelen eerder zichtbaar, zodat herstel kan worden ingepland voordat het werk als gereed wordt beschouwd.'], ['Maak ieder restpunt controleerbaar', 'Leg per punt vast wat niet voldoet, waar het zich bevindt, wie actie neemt en wanneer nacontrole plaatsvindt.'], ['Sluit pas na verificatie', 'Een melding dat iets is hersteld is niet hetzelfde als een gecontroleerde afhandeling.']],
      'renovatie-bewoners-hinder' => [['Plan vanuit het gebruik van het gebouw', 'Bereikbaarheid, geluid, stof, tijdelijke afsluitingen en voorzieningen bepalen hoe bewoners en gebruikers de uitvoering ervaren.'], ['Communiceer vóórdat hinder ontstaat', 'Planning, toegang, veiligheidsmaatregelen, contactpersonen en wijzigingen moeten tijdig en begrijpelijk worden gedeeld.'], ['Maak uitzonderingen onderdeel van de voorbereiding', 'Bij kwetsbare bewoners, afwijkende toegang of bijzondere gebruikssituaties is vooraf een passende werkwijze nodig.']],
      'glas-vervangen-verduurzamen' => [['Beoordeel eerst wat behouden blijft', 'Nieuw glas moet technisch passen bij kozijn, sponning, beslag en resterende levensduur.'], ['Kijk naar de hele gebouwschil', 'Het comfort- en energie-effect hangt ook af van kierdichting, gevel, ventilatie en andere zwakke delen.'], ['Vergelijk met het natuurlijke onderhoudsmoment', 'Als kozijnen of gevel binnenkort toch ingrijpend onderhoud vragen, kan combineren logischer zijn dan glas als losse maatregel.']],
      'isoleren-en-ventileren' => [['Minder lekverlies verandert de luchtverversing', 'Na isoleren en kierdichten kan ongecontroleerde luchttoevoer afnemen. De benodigde ventilatie moet daarom bewust worden georganiseerd.'], ['Kijk naar vochtproductie en gebruik', 'Bewoning, douchen, koken en bezetting beïnvloeden hoeveel vocht en verontreiniging moet worden afgevoerd.'], ['Beoordeel maatregelen als één systeem', 'Isolatie, luchtdichtheid en ventilatie moeten samen een gezond en comfortabel binnenklimaat ondersteunen.']],
      'gevelisolatie-aandachtspunten' => [['Begin bij de bestaande gevel', 'Materiaal, vochtbelasting, scheuren, aansluitingen en bestaande isolatie bepalen welke oplossingen technisch passend kunnen zijn.'], ['Werk details vooraf uit', 'Ramen, deuren, dakranden, plinten en doorvoeren zijn bepalend voor continuïteit van isolatie en waterdichting.'], ['Beoordeel vocht en uiterlijk', 'Een isolatiemaatregel verandert temperatuur- en vochtgedrag en kan ook vergunning- of esthetische gevolgen hebben.']],
      'verduurzamen-in-volgorde' => [['Start met toestand en doel', 'Bepaal eerst welke bouwdelen technisch aandacht vragen en welk resultaat u wilt bereiken.'], ['Respecteer technische afhankelijkheden', 'Een maatregel kan latere werkzaamheden moeilijker of duurder maken. Volgorde moet daarom rekening houden met gevel, glas, ventilatie en installaties.'], ['Koppel aan investeringsmomenten', 'Door maatregelen te combineren met gepland onderhoud kan dubbel werk worden voorkomen.']],
      'kierdichting-verduurzamen' => [['Vind eerst de ongecontroleerde lekken', 'Niet iedere opening is ongewenst: ventilatievoorzieningen hebben een functie. Maak daarom onderscheid tussen bedoelde toevoer en ongecontroleerde kieren.'], ['Controleer aansluitingen en draaiende delen', 'Kierdichting kan zitten in rubbers, beslag, aansluitnaden en bouwkundige details.'], ['Borg ventilatie na verbetering', 'Een luchtdichter gebouw vraagt om voldoende beheerste luchtverversing.']],
      'spouwmuur-naisoleren' => [['Onderzoek de spouw vóór uitvoering', 'Breedte, bestaande isolatie, vervuiling en onderbrekingen bepalen of de spouw geschikt is voor de beoogde maatregel.'], ['Controleer de buitengevel', 'Sterke vochtbelasting, beschadigd voegwerk of andere gebreken kunnen eerst aandacht vragen.'], ['Leg onzekerheden vast', 'Als delen van de spouw niet controleerbaar zijn, moet duidelijk zijn welke aannames worden gedaan en welk risico daarbij blijft bestaan.']],
      'zonwering-oververhitting' => [['Bepaal waar de warmtelast ontstaat', 'Oriëntatie, glasoppervlak, zoninstraling, interne warmte en gebruik bepalen samen het risico op hoge binnentemperaturen.'], ['Voorkom alleen symptoombestrijding', 'Koeling kan warmte afvoeren, terwijl buitenzonwering of andere bouwkundige maatregelen de instraling kunnen beperken. Welke aanpak past, is projectspecifiek.'], ['Neem bediening en gebruik mee', 'Een maatregel werkt alleen goed wanneer deze op het juiste moment wordt gebruikt of automatisch wordt geregeld.']],
      'verduurzaming-combineren-onderhoud' => [['Gebruik het moment dat een bouwdeel toch wordt aangepakt', 'Bereikbaarheid, demontage en afwerking hoeven dan niet volledig voor een tweede project te worden herhaald.'], ['Controleer de technische samenhang', 'Een energetische verbetering moet passen bij resterende bouwdelen, ventilatie en aansluitdetails.'], ['Maak scenario’s over meerdere jaren', 'Niet alles hoeft tegelijk. Een gefaseerd plan kan investeringen koppelen aan logische vervangings- en onderhoudsmomenten.']],
      'mjop-wat-is-het' => [['Een MJOP moet meer zijn dan een kalender', 'Een bruikbaar plan koppelt bouwdelen en maatregelen aan conditie, timing, hoeveelheden en verwachte kosten.'], ['Onderbouw waarom iets wanneer gebeurt', 'Prioriteit volgt uit risico, ontwikkeling en technische samenhang; niet alleen uit een theoretische levensduur.'], ['Actualiseer na inspectie en uitvoering', 'Nieuwe bevindingen, uitgevoerde werkzaamheden en prijsontwikkeling horen terug te komen in de planning.']],
      'gebrek-urgent' => [['Beoordeel het gevolg van niets doen', 'Veiligheid, waterindringing, gevolgschade, functieverlies en snelheid van verslechtering bepalen mede de urgentie.'], ['Maak verschil tussen urgent en belangrijk', 'Een kostbare toekomstige maatregel kan belangrijk zijn zonder vandaag acuut te zijn. Dat onderscheid helpt bij prioriteren.'], ['Leg tijdelijke maatregelen vast', 'Als definitief herstel niet direct kan, moet duidelijk zijn welke tijdelijke beheersmaatregel geldt en wanneer opnieuw wordt beoordeeld.']],
      'inspectie-frequentie' => [['Stem frequentie af op risico', 'Een kwetsbaar of kritisch bouwdeel vraagt mogelijk vaker aandacht dan een stabiel onderdeel met lage gevolgen bij uitval.'], ['Gebruik eerdere bevindingen', 'Verslechtering, reparaties en terugkerende klachten geven aanleiding om inspectie-interval aan te passen.'], ['Combineer inspecties waar logisch', 'Bereikbaarheid en samenhang kunnen het efficiënt maken meerdere bouwdelen in één opname te beoordelen.']],
      'onderhoud-prioriteren' => [['Begin met veiligheid en gevolgschade', 'Werkzaamheden met grote risico’s bij uitstel horen anders te worden gewogen dan voornamelijk esthetische gebreken.'], ['Vergelijk ontwikkeling en kosten', 'Een gebrek dat snel verslechtert kan eerder aandacht verdienen omdat later herstel omvangrijker wordt.'], ['Maak keuzes expliciet', 'Leg vast waarom iets nu, later of niet wordt uitgevoerd. Zo blijft de planning controleerbaar.']],
      'conditiemeting-gebouw' => [['Gebruik de score als gestructureerde waarneming', 'Een conditiescore helpt gebreken en toestand vergelijkbaar vast te leggen.'], ['Voeg oorzaak en risico toe', 'Dezelfde score kan bij verschillende bouwdelen een andere betekenis hebben voor veiligheid, gevolgschade of gebruik.'], ['Vertaal conditie niet automatisch naar vervanging', 'De maatregel volgt uit conditie, oorzaak, functie, risico en gewenste resterende levensduur samen.']],
      'onderhoudsbudget-reserveren' => [['Bouw het budget op uit verwachte maatregelen', 'Hoeveelheden, prijsniveau en geplande uitvoering geven een betere basis dan alleen historische uitgaven.'], ['Maak onzekerheid zichtbaar', 'Vroege ramingen bevatten onzekerheden in scope, prijzen en verborgen gebreken. Die horen expliciet in de reservering of bandbreedte.'], ['Actualiseer periodiek', 'Prijsontwikkeling, inspectieresultaten en gewijzigde prioriteiten veranderen de toekomstige kasbehoefte.']],
      'onderhoud-uitstellen-risico' => [['Bepaal wat er tijdens uitstel kan veranderen', 'Kijk naar snelheid van verslechtering, veiligheid, waterdichtheid, gevolgschade en beschikbaarheid van tijdelijke maatregelen.'], ['Vergelijk besparing met toekomstig risico', 'Een jaar later uitvoeren kan financieel logisch zijn, maar niet wanneer daardoor een veel grotere herstelomvang ontstaat.'], ['Leg de uitstelbeslissing vast', 'Noteer uitgangspunten, risico’s en het moment waarop opnieuw wordt geïnspecteerd of besloten.']],
      'gebouw-dossier-opbouwen' => [['Werk vanuit één herleidbare gebouwstructuur', 'Informatie wordt bruikbaarder wanneer foto’s, inspecties, tekeningen en werkzaamheden aan gebouw, bouwdeel en element kunnen worden gekoppeld.'], ['Bewaar besluiten naast technische informatie', 'Niet alleen wat is uitgevoerd, maar ook waarom een keuze is gemaakt helpt bij toekomstige beoordeling.'], ['Houd revisies actueel', 'Na uitvoering moeten gewijzigde gegevens, garanties en opleverinformatie terugkomen in het dossier zodat de volgende beslissing op de actuele situatie rust.']],
    ];
    return $guidance[$slug] ?? [];
  }

  private static function item(string $slug, string $title, string $summary): array {
    return [
      'slug' => $slug,
      'title' => $title,
      'summary' => $summary,
      'guidance' => self::guidance($slug),
      'public' => TRUE,
      'status' => KnowledgeApproval::STATUS_EDITORIAL,
      'ai_approved' => FALSE,
      'reviewed_by' => NULL,
      'reviewed_at' => NULL,
      'basis' => [
        'sources' => [],
        'validity_checked_at' => NULL,
        'notes' => 'Nog te voorzien van aantoonbare bron, geldigheidscontrole en deskundige beoordeling.',
      ],
    ];
  }

}
